### ISSUE TITLE
Create system to send messages between two users

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#1]
# Motivation
One core feature of a social media website is to be able to send messages to your friends. In this issue, we will be focusing on this functionality. Don't worry about the visuals (design isn't even done yet), just make sure that it works and is architecturally sound.

# Tasks
- [x] design a structure to store your data on firebase (together)
- [x] build the form that would send data to firebase (person 1)
- [x] setup the listener and create elements in the ui to display received and sent messages (person 2)

# Deliverables
- a "message window" component that lets you send and receive messages
  - the format of the firebase should make it so that different users (with some arbitrary user id) can send messages to each other and not have too much data duplication or latency

# Other Notes
- make sure that the firebase is structured in such a way that the messages are between two users
- discuss together and with me on how to best structure this data
- don't worry about the design. this can look disgusting, just make sure it works

**Comment by alexanderqchen** [comment]
Sorry, i reverted the associated PR because I messed up the eslint settings. I'm reopening this. Eslint should work properly now if you rebase with master and it should be checking your style more closely. I kind of just glanced over the PR, but I'll make sure to actually review it from now on.

**Comment by alexanderqchen** [comment]
Fixed here: https://github.com/UCLA-Creative-Labs/flux/commit/233155a2323716177ab9738bc47933a73f363bd6
