### ISSUE TITLE
Integrate messages and posts with users

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#10]
# Motivation
Posts and messages are specifically linked with users, so the firebase should reflect that.

# Tasks
- [ ] Link messages with users
- [ ] Link posts with users

# Deliverables
- [ ] Sending a message should update the users branch accordingly if necessary
- [ ] Making a post should update the users branch accordingly if necessary

**Comment by alexanderqchen** [comment]
https://github.com/UCLA-Creative-Labs/flux/pull/28
https://github.com/UCLA-Creative-Labs/flux/pull/26
