### ISSUE TITLE
Create system to make posts

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#2]
# Motivation
One of the major features of a social media websites is to make posts to the public. I plan on making all posts public for simplicity and because I think this is optimal for this kind of art project. This is because not all users will be using this with a friend, but should still be able to see posts and play around with the features.

# Tasks
- [x] design a structure to store your data on firebase (together)
- [x] build the form that would send data to firebase (person 1)
- [x] setup the listener and create elements in the ui to display received and sent posts (person 2)

# Deliverable
- a news feed component that has a "make a post" and "show the posts" subcomponents that read and write to firebase with text, link, and photo data

# Other Notes
- This should support multiple data formats including text, links, photos
- discuss together and with me on how to best structure this data
- don't worry about the design. this can look disgusting, just make sure it works

**Comment by kandrewz** [comment]
treat text and links as one data type and photos as another. store photos on firebase

**Comment by ryanlam53** [comment]
finished up uploading and displaying post data

**Comment by alexanderqchen** [comment]
If you're done with this issue, make a pull request! I'm going to reopen this issue until an associated pull request is merged into master.
