### ISSUE TITLE
Setup authentication

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#3]
# Motivation
This is an essential part of any website with user accounts. People need to have their account information saved along with their messages and posts.

# Tasks
- [x] integrate with authentication service (fb auth, 0auth, firebase auth, etc.)
- [ ] create form for storing other information about user
- [ ] store this data in firebase

# Other Notes
- don't care about design yet, just make sure it works
- Decide what authentication service to use at 4/19 meeting
