### ISSUE TITLE
Implement liking posts

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#7]
# Motivation
Getting likes makes you feel good, so let's make that happen. It's also real useful for machine learning~ because we're totally doing that.

# Tasks
- [x] have a like button that updates firebase
- [x] show how many people liked each post
- [ ] show what posts a specific user liked

# Deliverables
- The post component has a like button and the number of likes it already has
- A page that shows all the posts you like

**Comment by kandrewz** [comment]
added like button that increments likes, updates firebase, and displays the new likes 
forgot to add type="submit" to the button and it made ~20,000 updates before ryan and I shut it down :(

**Comment by kandrewz** [comment]
added function so that firebase stores an array of liked posts, however problem is that array is being overwritten instead of appending
