### ISSUE TITLE
Create friends and user profile page

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#8]
# Motivation
It's nice to have friends. It's also nice to see what you or someone else has posted.

# Tasks
- [ ] create a user profile page
- [ ] implement being able to add a friend

# Deliverables
- [ ] A user profile page that lists all the user's posts
- [ ] An add friend button that updates the firebase
