### ISSUE TITLE
Create section for messaging friends

### ISSUE THREAD

**Issue by alexanderqchen** [UCLA-Creative-Labs/flux#9]
# Motivation
You should be able to have all your friends listed to message them.

# Tasks
- [x] Display a list of your friends on the page
- [x] When you click on a friend make it bring up a messaging window
- [x] In that window show your conversation with that friend
- [x] Send and receive messages through that window

# Deliverables
- [x] Component to list friends
- [x] Message window component that works
